services:
    db:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel
        depends_on:
            - db
    node:
        image: node:latest
        command: bash -c "
            npm install
            && npm run dev --host
            "
        working_dir: /var/www/html
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
        depends_on:
            - app
    webserver:
        image: nginx:alpine
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/snippets:/etc/nginx/snippets
        networks:
            - laravel
        depends_on:
            - app


networks:
    laravel:

volumes:
    dbdata:
